-- Solo lectura: catálogo de public; no consulta filas de mediciones.
select json_build_object(
'relations',(select json_agg(row_to_json(x)) from (select c.relname,c.relkind,c.relrowsecurity,c.relforcerowsecurity,pg_get_userbyid(c.relowner) as owner,c.relacl,obj_description(c.oid) as comment from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in ('r','p','v','m','S','f') order by c.relname) x),
'columns',(select json_agg(row_to_json(x)) from (select c.relname,a.attname,a.attnum,format_type(a.atttypid,a.atttypmod) as type,a.attnotnull,a.attidentity,a.attgenerated,pg_get_expr(d.adbin,d.adrelid) as default_expr,col_description(c.oid,a.attnum) as comment from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_attribute a on a.attrelid=c.oid left join pg_attrdef d on d.adrelid=c.oid and d.adnum=a.attnum where n.nspname='public' and c.relkind in ('r','p','v','m','f') and a.attnum>0 and not a.attisdropped order by c.relname,a.attnum) x),
'constraints',(select json_agg(row_to_json(x)) from (select c.conname,c.contype,c.conrelid::regclass::text as relation,pg_get_constraintdef(c.oid,true) as definition,c.convalidated from pg_constraint c join pg_namespace n on n.oid=c.connamespace where n.nspname='public' order by c.conname) x),
'indexes',(select json_agg(row_to_json(x)) from (select tablename,indexname,indexdef from pg_indexes where schemaname='public' order by indexname) x),
'policies',(select json_agg(row_to_json(x)) from (select * from pg_policies where schemaname='public' order by tablename,policyname) x),
'triggers',(select json_agg(row_to_json(x)) from (select c.relname,t.tgname,pg_get_triggerdef(t.oid,true) as definition,t.tgenabled from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and not t.tgisinternal order by t.tgname) x),
'functions',(select json_agg(row_to_json(x)) from (select p.proname,p.prokind,pg_get_function_identity_arguments(p.oid) as args,case when p.prokind in ('f','p') then pg_get_functiondef(p.oid) end as definition from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and not exists (select 1 from pg_depend d where d.classid='pg_proc'::regclass and d.objid=p.oid and d.deptype='e') order by p.proname) x),
'sequences',(select json_agg(row_to_json(x)) from (select c.relname,format_type(s.seqtypid,null) as type,s.seqstart::text,s.seqincrement::text,s.seqmax::text,s.seqmin::text,s.seqcache::text,s.seqcycle from pg_sequence s join pg_class c on c.oid=s.seqrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' order by c.relname) x),
'enums',(select json_agg(row_to_json(x)) from (select t.typname,e.enumlabel,e.enumsortorder from pg_type t join pg_namespace n on n.oid=t.typnamespace join pg_enum e on e.enumtypid=t.oid where n.nspname='public' order by t.typname,e.enumsortorder) x),
'grants',(select json_agg(row_to_json(x)) from (select table_name,grantee,privilege_type,is_grantable from information_schema.table_privileges where table_schema='public' order by table_name,grantee,privilege_type) x),
'default_acl',(select json_agg(row_to_json(x)) from (select pg_get_userbyid(d.defaclrole) as role,d.defaclobjtype,d.defaclacl from pg_default_acl d join pg_namespace n on n.oid=d.defaclnamespace where n.nspname='public' order by role,defaclobjtype) x),
'schema',(select json_build_object('owner',pg_get_userbyid(n.nspowner),'acl',n.nspacl) from pg_namespace n where n.nspname='public')
) as schema_snapshot;
